### ISSUE TITLE
generate_replay created a video.mp4 file locally

### ISSUE THREAD

**Issue by osanseviero** [huggingface/huggingface_sb3#14]
This code snippet

```
env = VecVideoRecorder(
        eval_env,
        "./",  # Temporary video folder
        record_video_trigger=lambda x: x == 0,
        video_length=video_length,
        name_prefix="",
    )
```

generated a video file wherever the user is. In the temporary video folder, you can use `tempfile.TemporaryDirectory()` to automatically create a directory that will be deleted afterwards

**Comment by simoninithomas** [comment]
I can close this issue ? It was solved with your #15
