### ISSUE TITLE
Cloudpickle dependency pinned to 1.6

### ISSUE THREAD

**Issue by ernestum** [huggingface/huggingface_sb3#16]
Is there any reason why the cloudpickle dependency is fixed to 1.6? I had no issue uploading using 2.1.0 but maybe I was just lucky?

**Comment by ernestum** [comment]
@simoninithomas do you have a hint for me? This is causing me quite a bad headache when uploading models for the [seals environments](https://github.com/HumanCompatibleAI/seals)

**Comment by ernestum** [comment]
I just realized, that `cloudpickle` is not even used by this library. I am confused :thinking:

**Comment by simoninithomas** [comment]
Hi, sorry for the (big) delay. Don't hesitate to send me a mail if it happens again and you need a fast answer.
I know SB3 is using cloudpickle to serialize the models. 

Normally we removed it in version 2.0 but it seems I made a mistake when I published v.2.2.1. I removing the = 1.6 right now.

**Comment by simoninithomas** [comment]
Ok made some tests and normally everything works. I published the new version v2.2.2.

I let this issue open, tell me if it works better for you now 🤗 .

**Comment by ernestum** [comment]
Awesome, thanks for fixing! I will send an email in the future if it is urgent.
I will test it later and report back/close the issue.

As for the Colab issue, I am a bit confused for two reasons:
1. Why do you need `cloudpickle>=1.6`? The reason must lie in some dependency of `huggingface_sb3` since it is not used in `huggingface_sb3`. But then why is this requirement not properly encoded in the dependencies of that dependency?
2. So you decided to patch the issue via adding `cloudpickle` to the dependencies of `huggingface_sb3`. But why did you not add `>=1.6` in [this line of setup.py](https://github.com/huggingface/huggingface_sb3/blob/141fbff9dc02dbe65f751407298b8dcd224dc2f5/setup.py#L8)?

I would recommend to figure out what package needs version >= 1.6 after all and then add the dependency there.
If you want to patch the issue within `huggingface_sb3`, then maybe introduce a "colab" extra? Then we can do `!pip install huggingface_sb3[colab]` and it is clear that the dependency was only added for the Colab issue.

**Comment by ernestum** [comment]
In the end the source of the entire issue lies in the wrong usage of cloudpickle in SB3.
I just cite the cloudpickle readme here:

> Using cloudpickle for long-term object storage is not supported and strongly discouraged.

**Comment by simoninithomas** [comment]
I will start to check what package 🕵️. I did not add >=1.6 since I thought the default version was higher by default in colab and in general. In the meantime does you still have problem uploading to the Hub/ loading from Hub?
