### ISSUE TITLE
package_to_hub requires OpenGL and xvfb which are not present on newer Mac OS systems

### ISSUE THREAD

**Issue by marcin-sobocinski** [huggingface/huggingface_sb3#20]
Currently package_to_hub works only for OpenGL capable computers. It doesn't support any other option for generating video and it doesn't allow to upload model without a video. All new Mac OSes don't have OpenGL support any more.

**Comment by araffin** [comment]
Hello,
I don't have any Mac OS machine so I cannot test myself.

@marcin-sobocinski what is the exact error? could you provide a minimal code example with traceback?

as an alternative, you could use google colab or you could also skip recording video? (@simoninithomas you should probably allow to skip that step when using package to hub, as we do in the RL Zoo https://github.com/DLR-RM/rl-baselines3-zoo/blob/master/rl_zoo3/push_to_hub.py#L241)

>  alternative to xvfb

xvfb should only be for headless machine.

**Comment by marcin-sobocinski** [comment]
OK. I used alternative install path (via conda package manager) and it looks like working now. At least the model was uploaded with the video to the hugging face. Sorry to bother you. I am closing the issue.
