### ISSUE TITLE
Unable to save the replay to hub. Error: must be real number, not NoneType

### ISSUE THREAD

**Issue by zoctipus** [huggingface/huggingface_sb3#29]

**Comment by zoctipus** [comment]
1.

**Comment by flerovious** [comment]
In case you're using brew on an m-series mac and having trouble fixing, here's what I did:

1. Install ffmpeg version 4 with `brew install ffmpeg@4` as suggested in https://github.com/Zulko/moviepy/issues/1867#issuecomment-1345275334
2. Check that ffmpeg 4.4.4 (latest version for ffmpeg 4) is installed. Mine was installed at `/opt/homebrew/Cellar/ffmpeg@4/4.4.4/bin/ffmpeg`
3. Create or add the following environment variable to your `.env` file, which will be read by moviepy.
```bash
FFMPEG_BINARY="/opt/homebrew/Cellar/ffmpeg@4/4.4.4/bin/ffmpeg"
```
4. Check that moviepy loads ffmpeg successfully with the following python script
```python
from moviepy.config import *

if try_cmd([FFMPEG_BINARY])[0]:
    print( "MoviePy : ffmpeg successfully found." )
else:
    print( "MoviePy : can't find or access ffmpeg." )
```
