### ISSUE TITLE
VecEnvWrapper.render() got an unexpected keyword argument 'render_mode'

### ISSUE THREAD

**Issue by nsanghi** [huggingface/huggingface_sb3#33]
The commit 2e3d728 in branch gymnasium added the code shown below in line 152 and 153
```{python}
                # Force rgb_array rendering
                env.render(render_mode="rgb_array")
```

It gives an error with latest sb3@2.0.0 

```
VecEnvWrapper.render() got an unexpected keyword argument 'render_mode'
We are unable to generate a replay of your agent, the package_to_hub process continues
```

The issue is that `VecEnvWrapper.render()` has a render method which takes argument `mode` and not `render_mode`

Pls change this line `env.render(render_mode="rgb_array")` to `env.render(mode="rgb_array")`

I can raise a PR

**Comment by simoninithomas** [comment]
Hey there 👋 what you can do is try our new PR and normally it should work 🤗 
pip install git+https://github.com/huggingface/huggingface_sb3@gymnasium-v2
