### ISSUE TITLE
Release v.2.3 breaks backwards compatibility

### ISSUE THREAD

**Issue by ernestum** [huggingface/huggingface_sb3#37]
The switch to `gymnasium` is not backwards compatible, therefore release v2.3 should have been v3.0.

[SemVer recommends doing a v2.3.1 release with the state of v2.2.5 and then doing a v3.0 release with the state of v2.3.0](https://semver.org/#what-do-i-do-if-i-accidentally-release-a-backward-incompatible-change-as-a-minor-version)

**Comment by ernestum** [comment]
Workaround in the meantime: pin `huggingface_sb3` version with `huggingface_sb3==2.2.5`

**Comment by simoninithomas** [comment]
Hey there 👋 should be ✅. I agree it would be cleaner this way. Thanks for your help 🤗

**Comment by ernestum** [comment]
Awesome thank!
