### ISSUE TITLE
Add support for VecNormalize

### ISSUE THREAD

**Issue by araffin** [huggingface/huggingface_sb3#6]
Detect and save automatically normalization when present (using for instance `unwrap_vec_normalize()` helper).

**Comment by simoninithomas** [comment]
On it!

**Comment by araffin** [comment]
> vecnorm = model.get_vec_normalize_env()

you should use `unwrap_vec_normalize` because you are usually using an eval env not connected to the model (for instance when you load the model), otherwise the rest is correct ;)

**Comment by simoninithomas** [comment]
So in this case it implies that I need to add a env parameter to package_to_hub.

**Comment by araffin** [comment]
https://github.com/huggingface/huggingface_sb3/blob/2c898f15afe3bec93dd3a7c181096b442c8cafd1/huggingface_sb3/push_to_hub.py#L246

That's already the case, no?

**Comment by araffin** [comment]
Oh, looking at your implementation, I think we are thinking differently.
I just wanted to save the stats if needed and keep the rest the same (assuming that eval env is already properly wrapped).

**Comment by araffin** [comment]
> We have env that is a vec env. When we train our model model.learn(env), we also normalize the environment (input features and reward).

yes, unless you load a model (for instance best model using eval callback)

>  because if I get the one from the eval_env they are useless since they were not updated during the training right?

It depends how you define eval env, but normally you should already use the stats from the training env.
In the eval callback, we actually synchronize the two.

> (that I assume being properly wrapped) 

properly wrapped for me also mean that it has the correct stats, so you could discard `model.env` completely.

> So my idea was:

this would work only if you do the packaging right after training and it requires that the model has an env


My idea was simpler:
- assume eval env is properly wrapped and with the correct stats
- evaluate as usual but save the stats using the eval env
